# Generated by Django 5.1.5 on 2025-02-11 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_path', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField(null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_death', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('publicity', models.BooleanField(default=False)),
                ('date_publicity', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ensemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('foundation_date', models.DateField(null=True)),
                ('dissolution_date', models.DateField(blank=True, null=True)),
                ('guest', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
                ('publicity', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GenreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('play_character', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RepeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('publicity', models.BooleanField(default=False)),
                ('concert_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_app.concerttype')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.concert')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.concert')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_app.employeetype'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ensemble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_app.ensemble'),
        ),
        migrations.AddField(
            model_name='employee',
            name='genre_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_app.genretype'),
        ),
        migrations.CreateModel(
            name='EmployeeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.job')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('author_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('publicity', models.BooleanField(default=False)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('ensemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.ensemble')),
                ('genre_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_app.genretype')),
            ],
        ),
        migrations.CreateModel(
            name='PlayDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.document')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.play')),
            ],
        ),
        migrations.CreateModel(
            name='PlayPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archive_app.employee')),
                ('employee_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.employeejob')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.play')),
            ],
        ),
        migrations.CreateModel(
            name='Repeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('publicity', models.BooleanField(default=False)),
                ('ensemble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_app.ensemble')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.play')),
                ('repeat_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_app.repeattype')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_app.room')),
            ],
        ),
        migrations.CreateModel(
            name='RepeatPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.employeejob')),
                ('repeat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.repeat')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
