# Generated by Django 5.1.3 on 2025-02-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_path',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
