# Generated by Django 5.1.3 on 2024-12-11 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConcertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RepeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='play',
        ),
        migrations.RemoveField(
            model_name='employeejob',
            name='play',
        ),
        migrations.AddField(
            model_name='employeejob',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeejob',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeejob',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.employee'),
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='genretype',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='repeat',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.play'),
        ),
        migrations.CreateModel(
            name='ConcertDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.concert')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.document')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.concert')),
                ('employee_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.employeejob')),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='concert_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_app.concerttype'),
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.employee')),
            ],
        ),
        migrations.AlterField(
            model_name='employeejob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.job'),
        ),
        migrations.CreateModel(
            name='PlayDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.document')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.play')),
            ],
        ),
        migrations.CreateModel(
            name='PlayPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.employeejob')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.play')),
            ],
        ),
        migrations.CreateModel(
            name='RepeatPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.employeejob')),
                ('repeat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.repeat')),
            ],
        ),
        migrations.AddField(
            model_name='repeat',
            name='repeat_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_app.repeattype'),
        ),
    ]
