# Generated by Django 5.1.3 on 2025-01-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playperformer',
            name='employee',
        ),
    ]
