# Generated by Django 5.1.3 on 2025-01-25 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0002_remove_playperformer_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='playperformer',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archive_app.employee'),
        ),
    ]
