# Generated by Django 5.1.3 on 2025-01-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0003_playperformer_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='play_character',
            field=models.BooleanField(default=False),
        ),
    ]
