# Generated by Django 5.1.3 on 2025-01-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
