# Generated by Django 5.1.3 on 2025-02-16 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0004_delete_repeatdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.document')),
                ('repeat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_app.repeat')),
            ],
        ),
    ]
