# Generated by Django 5.1.5 on 2025-02-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0004_job_play_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='publicity',
            field=models.BooleanField(default=False),
        ),
    ]
