# Generated by Django 5.1.3 on 2025-01-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0004_alter_userprofile_real_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
