# Generated by Django 5.1.3 on 2025-02-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0005_repeatdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepeatDocument',
        ),
    ]
