# Generated by Django 5.1.3 on 2025-02-04 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0005_employee_publicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_death',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='genre_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_app.genretype'),
        ),
        migrations.AddField(
            model_name='employee',
            name='place_of_death',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
