# Generated by Django 5.1.5 on 2025-02-08 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0006_employee_date_of_death_employee_genre_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concertperformer',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='repeatperformer',
            name='employee_job',
        ),
        migrations.AddField(
            model_name='concertperformer',
            name='employee_job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='archive_app.employeejob'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_app.document'),
        ),
        migrations.AddField(
            model_name='ensemble',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='ensemble',
            name='guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='play',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='repeat',
            name='ensemble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_app.ensemble'),
        ),
        migrations.AddField(
            model_name='repeatperformer',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='archive_app.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repeatperformer',
            name='role',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concert',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='play',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
