# Generated by Django 5.1.5 on 2025-02-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0007_remove_concertperformer_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemble',
            name='publicity',
            field=models.BooleanField(default=False),
        ),
    ]
