# Generated by Django 5.1.5 on 2025-02-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0008_ensemble_publicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='publicity',
            field=models.BooleanField(default=False),
        ),
    ]
