# Generated by Django 5.1.5 on 2025-02-09 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0009_concert_publicity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concertperformer',
            name='employee_job',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='document',
        ),
        migrations.RemoveField(
            model_name='repeatperformer',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='repeatperformer',
            name='role',
        ),
        migrations.AddField(
            model_name='concertperformer',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='archive_app.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='date_publicity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repeatperformer',
            name='employee_job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='archive_app.employeejob'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concert',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ensemble',
            name='foundation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='play',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playperformer',
            name='job',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
